/**
 * Phase C — User Approval & Explainable Recommendations View
 * Module: Sudhanshu
 * 
 * Objective:
 * Interactive human-in-the-loop control interface for reviewing, editing,
 * approving, or rejecting explainable recommendations generated by the system.
 */

import { useState, useMemo } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { usePhaseC } from './PhaseCContext';
import { useDataset } from '../contexts/DatasetContext';
import { 
  CheckCircle2, 
  XCircle, 
  MinusCircle, 
  Edit3, 
  Sparkles, 
  Search, 
  ArrowRight, 
  ShieldCheck, 
  AlertTriangle, 
  Copy, 
  Activity, 
  HelpCircle,
  SlidersHorizontal,
  CheckCheck,
  RotateCcw,
  Zap,
  Info
} from 'lucide-react';

export default function CleaningActionsView() {
  const navigate = useNavigate();
  const { originalDataset } = useDataset();
  const {
    recommendations,
    approveRecommendation,
    rejectRecommendation,
    ignoreRecommendation,
    editRecommendation,
    approveAllHighConfidence,
    approveAll,
    rejectAll,
    resetApprovals,
    executeCleaning
  } = usePhaseC();

  // Local filtering & modal state
  const [activeCategory, setActiveCategory] = useState('All');
  const [activeConfidence, setActiveConfidence] = useState('All');
  const [activeStatus, setActiveStatus] = useState('All');
  const [searchQuery, setSearchQuery] = useState('');
  
  // Edit modal state
  const [editingRec, setEditingRec] = useState(null);
  const [editValue, setEditValue] = useState('');
  const [editAction, setEditAction] = useState('');
  const [toastMessage, setToastMessage] = useState(null);

  const showToast = (msg) => {
    setToastMessage(msg);
    setTimeout(() => setToastMessage(null), 3000);
  };

  // Compute category counts
  const counts = useMemo(() => {
    const total = recommendations.length;
    const highConf = recommendations.filter(r => r.confidenceLevel === 'High').length;
    const pending = recommendations.filter(r => r.status === 'pending').length;
    const approved = recommendations.filter(r => r.status === 'approved' || r.status === 'edited').length;
    const rejected = recommendations.filter(r => r.status === 'rejected').length;

    const categories = {
      Duplicates: recommendations.filter(r => r.category === 'Duplicates').length,
      Anomalies: recommendations.filter(r => r.category === 'Anomalies').length,
      'Rule Violations': recommendations.filter(r => r.category === 'Rule Violations').length,
      Inconsistencies: recommendations.filter(r => r.category === 'Inconsistencies').length,
      'Missing Values': recommendations.filter(r => r.category === 'Missing Values').length
    };

    return { total, highConf, pending, approved, rejected, categories };
  }, [recommendations]);

  // Filtered recommendations
  const filteredRecs = useMemo(() => {
    return recommendations.filter(rec => {
      // Category filter
      if (activeCategory !== 'All' && rec.category !== activeCategory) return false;
      // Confidence filter
      if (activeConfidence !== 'All' && rec.confidenceLevel !== activeConfidence) return false;
      // Status filter
      if (activeStatus !== 'All' && rec.status !== activeStatus) return false;
      // Search query
      if (searchQuery.trim()) {
        const q = searchQuery.toLowerCase();
        const matchTitle = rec.issueTitle.toLowerCase().includes(q);
        const matchCol = rec.column.toLowerCase().includes(q);
        const matchExpl = rec.explanation.toLowerCase().includes(q);
        const matchVal = String(rec.currentValue).toLowerCase().includes(q);
        if (!matchTitle && !matchCol && !matchExpl && !matchVal) return false;
      }
      return true;
    });
  }, [recommendations, activeCategory, activeConfidence, activeStatus, searchQuery]);

  // Handle open edit modal
  const handleOpenEdit = (rec) => {
    setEditingRec(rec);
    setEditValue(rec.userCustomValue !== null ? rec.userCustomValue : rec.suggestedValue);
    setEditAction(rec.suggestedAction || 'replace_value');
  };

  const handleSaveEdit = () => {
    if (editingRec) {
      editRecommendation(editingRec.id, editValue, editAction);
      showToast(`Custom value saved for ${editingRec.issueTitle}`);
      setEditingRec(null);
    }
  };

  const handleExecuteAndProceed = () => {
    executeCleaning();
    navigate('/cleaned-preview');
  };

  if (!originalDataset || !originalDataset.rows) {
    return (
      <div className="animate-fade-in max-w-5xl mx-auto flex flex-col items-center justify-center min-h-[500px] text-center p-8">
        <div className="w-20 h-20 bg-blue-50 dark:bg-blue-500/10 rounded-full flex items-center justify-center mb-6 border border-blue-100 dark:border-blue-500/20">
          <ShieldCheck className="w-10 h-10 text-blue-500" />
        </div>
        <h2 className="text-3xl font-bold text-slate-800 dark:text-white mb-3">No Dataset Loaded</h2>
        <p className="text-slate-500 dark:text-[#8ba3c9] max-w-md mb-8">
          Upload a CSV dataset and perform profiling/scanning to generate explainable recommendations.
        </p>
        <Link
          to="/upload"
          className="px-8 py-3.5 bg-blue-600 hover:bg-blue-500 text-white rounded-xl shadow-lg font-medium transition-all"
        >
          Go to Upload
        </Link>
      </div>
    );
  }

  return (
    <div className="animate-fade-in max-w-7xl mx-auto text-slate-800 dark:text-white transition-colors duration-500 pb-28">
      {/* Toast alert */}
      {toastMessage && (
        <div className="fixed top-6 right-6 z-50 bg-slate-900 dark:bg-blue-900/90 text-white px-5 py-3 rounded-xl shadow-2xl border border-blue-500/30 flex items-center gap-3 animate-bounce">
          <Sparkles className="w-5 h-5 text-emerald-400" />
          <span className="text-sm font-medium">{toastMessage}</span>
        </div>
      )}

      {/* Header Section */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="px-3 py-1 bg-indigo-100 text-indigo-700 dark:bg-indigo-500/20 dark:text-indigo-300 rounded-full text-xs font-semibold tracking-wider uppercase flex items-center gap-1.5">
              <Zap className="w-3.5 h-3.5" />
              Phase C — User Approval Engine
            </span>
            <span className="text-xs text-slate-400 dark:text-[#8ba3c9]">Human-in-the-Loop</span>
          </div>
          <h2 className="text-3xl font-bold tracking-tight text-slate-900 dark:text-white">
            Explainable Cleaning Recommendations
          </h2>
          <p className="text-slate-500 dark:text-[#8ba3c9] mt-1 font-light text-sm">
            Review detection evidence, customize actions, and approve cleaning operations with full auditability.
          </p>
        </div>

        {/* Global Bulk Action Buttons */}
        <div className="flex flex-wrap items-center gap-2.5">
          <button
            onClick={() => {
              approveAllHighConfidence();
              showToast('Approved all High-Confidence (≥90%) recommendations!');
            }}
            className="px-4 py-2.5 bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-500 hover:to-teal-500 text-white text-xs font-bold rounded-xl shadow-md shadow-emerald-600/20 flex items-center gap-2 transition-all hover:scale-[1.02] active:scale-[0.98]"
          >
            <Sparkles className="w-4 h-4 text-emerald-200" />
            Approve All High Confidence ({counts.highConf})
          </button>

          <button
            onClick={() => {
              approveAll();
              showToast('Approved all pending recommendations');
            }}
            className="px-3.5 py-2.5 bg-slate-100 dark:bg-[#0a1e45] text-slate-700 dark:text-slate-200 hover:bg-emerald-50 dark:hover:bg-emerald-950/40 hover:text-emerald-600 text-xs font-semibold rounded-xl border border-slate-200 dark:border-[#1a325a] flex items-center gap-1.5 transition-colors"
          >
            <CheckCheck className="w-4 h-4" />
            Approve All
          </button>

          <button
            onClick={() => {
              rejectAll();
              showToast('Rejected all recommendations');
            }}
            className="px-3.5 py-2.5 bg-slate-100 dark:bg-[#0a1e45] text-slate-700 dark:text-slate-200 hover:bg-rose-50 dark:hover:bg-rose-950/40 hover:text-rose-600 text-xs font-semibold rounded-xl border border-slate-200 dark:border-[#1a325a] flex items-center gap-1.5 transition-colors"
          >
            <XCircle className="w-4 h-4" />
            Reject All
          </button>

          <button
            onClick={() => {
              resetApprovals();
              showToast('Reset all recommendations to pending status');
            }}
            className="p-2.5 bg-slate-100 dark:bg-[#0a1e45] text-slate-500 dark:text-slate-400 hover:text-slate-800 dark:hover:text-white rounded-xl border border-slate-200 dark:border-[#1a325a] transition-colors"
            title="Reset Approvals"
          >
            <RotateCcw className="w-4 h-4" />
          </button>
        </div>
      </div>

      {/* KPI Stats Bar */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-8">
        <div className="bg-white dark:bg-[#05142e]/80 backdrop-blur-sm p-4 rounded-2xl border border-slate-200 dark:border-[#1a325a] shadow-sm flex items-center gap-3.5">
          <div className="p-3 bg-blue-50 dark:bg-blue-500/10 text-blue-600 dark:text-blue-400 rounded-xl">
            <SlidersHorizontal className="w-5 h-5" />
          </div>
          <div>
            <p className="text-xs text-slate-400 font-medium">Total Detected</p>
            <h4 className="text-2xl font-bold text-slate-900 dark:text-white">{counts.total}</h4>
          </div>
        </div>

        <div className="bg-white dark:bg-[#05142e]/80 backdrop-blur-sm p-4 rounded-2xl border border-slate-200 dark:border-[#1a325a] shadow-sm flex items-center gap-3.5">
          <div className="p-3 bg-amber-50 dark:bg-amber-500/10 text-amber-600 dark:text-amber-400 rounded-xl">
            <HelpCircle className="w-5 h-5" />
          </div>
          <div>
            <p className="text-xs text-slate-400 font-medium">Pending Review</p>
            <h4 className="text-2xl font-bold text-amber-600 dark:text-amber-400">{counts.pending}</h4>
          </div>
        </div>

        <div className="bg-white dark:bg-[#05142e]/80 backdrop-blur-sm p-4 rounded-2xl border border-slate-200 dark:border-[#1a325a] shadow-sm flex items-center gap-3.5">
          <div className="p-3 bg-emerald-50 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 rounded-xl">
            <CheckCircle2 className="w-5 h-5" />
          </div>
          <div>
            <p className="text-xs text-slate-400 font-medium">Approved Actions</p>
            <h4 className="text-2xl font-bold text-emerald-600 dark:text-emerald-400">{counts.approved}</h4>
          </div>
        </div>

        <div className="bg-white dark:bg-[#05142e]/80 backdrop-blur-sm p-4 rounded-2xl border border-slate-200 dark:border-[#1a325a] shadow-sm flex items-center gap-3.5">
          <div className="p-3 bg-purple-50 dark:bg-purple-500/10 text-purple-600 dark:text-purple-400 rounded-xl">
            <Sparkles className="w-5 h-5" />
          </div>
          <div>
            <p className="text-xs text-slate-400 font-medium">High Confidence</p>
            <h4 className="text-2xl font-bold text-purple-600 dark:text-purple-400">{counts.highConf}</h4>
          </div>
        </div>
      </div>

      {/* Filter & Search Bar */}
      <div className="bg-white dark:bg-[#05142e]/80 backdrop-blur-sm p-5 rounded-2xl border border-slate-200 dark:border-[#1a325a] shadow-sm mb-6 space-y-4">
        {/* Category Pills */}
        <div className="flex flex-wrap items-center gap-2">
          {['All', 'Duplicates', 'Anomalies', 'Rule Violations', 'Inconsistencies', 'Missing Values'].map(cat => {
            const count = cat === 'All' ? counts.total : (counts.categories[cat] || 0);
            const isActive = activeCategory === cat;
            return (
              <button
                key={cat}
                onClick={() => setActiveCategory(cat)}
                className={`px-3.5 py-1.5 rounded-xl text-xs font-semibold transition-all flex items-center gap-2 ${
                  isActive
                    ? 'bg-blue-600 text-white shadow-md shadow-blue-500/20'
                    : 'bg-slate-100 dark:bg-[#0a1e45] text-slate-600 dark:text-[#8ba3c9] hover:bg-slate-200 dark:hover:bg-[#132c5e]'
                }`}
              >
                <span>{cat}</span>
                <span className={`px-1.5 py-0.2 rounded-full text-[10px] ${
                  isActive ? 'bg-white/20 text-white' : 'bg-slate-200 dark:bg-[#1a325a] text-slate-600 dark:text-slate-300'
                }`}>
                  {count}
                </span>
              </button>
            );
          })}
        </div>

        {/* Secondary Filters & Search */}
        <div className="flex flex-col sm:flex-row items-center justify-between gap-3 pt-3 border-t border-slate-100 dark:border-[#1a325a]/60">
          <div className="flex flex-wrap items-center gap-3 w-full sm:w-auto">
            {/* Confidence Filter */}
            <div className="flex items-center gap-2 text-xs">
              <span className="text-slate-400 font-medium">Confidence:</span>
              {['All', 'High', 'Medium', 'Low'].map(lvl => (
                <button
                  key={lvl}
                  onClick={() => setActiveConfidence(lvl)}
                  className={`px-2.5 py-1 rounded-lg font-medium text-xs transition-colors ${
                    activeConfidence === lvl
                      ? 'bg-indigo-100 dark:bg-indigo-500/20 text-indigo-700 dark:text-indigo-300 font-bold'
                      : 'text-slate-500 dark:text-[#8ba3c9] hover:text-slate-800 dark:hover:text-white'
                  }`}
                >
                  {lvl}
                </button>
              ))}
            </div>

            {/* Status Filter */}
            <div className="flex items-center gap-2 text-xs pl-2 border-l border-slate-200 dark:border-[#1a325a]">
              <span className="text-slate-400 font-medium">Status:</span>
              {['All', 'pending', 'approved', 'rejected', 'ignored'].map(st => (
                <button
                  key={st}
                  onClick={() => setActiveStatus(st)}
                  className={`px-2.5 py-1 rounded-lg font-medium text-xs capitalize transition-colors ${
                    activeStatus === st
                      ? 'bg-blue-100 dark:bg-blue-500/20 text-blue-700 dark:text-blue-300 font-bold'
                      : 'text-slate-500 dark:text-[#8ba3c9] hover:text-slate-800 dark:hover:text-white'
                  }`}
                >
                  {st}
                </button>
              ))}
            </div>
          </div>

          {/* Search Input */}
          <div className="relative w-full sm:w-64">
            <Search className="w-4 h-4 text-slate-400 absolute left-3 top-2.5" />
            <input
              type="text"
              placeholder="Search issues, columns..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-9 pr-3 py-1.5 text-xs rounded-xl bg-slate-50 dark:bg-[#0a1e45] border border-slate-200 dark:border-[#1a325a] text-slate-800 dark:text-white focus:outline-none focus:border-blue-500 transition-colors"
            />
          </div>
        </div>
      </div>

      {/* Recommendations Cards Grid */}
      {filteredRecs.length === 0 ? (
        <div className="bg-white dark:bg-[#05142e]/80 backdrop-blur-sm p-12 rounded-2xl border border-slate-200 dark:border-[#1a325a] text-center text-slate-400">
          <CheckCircle2 className="w-12 h-12 mx-auto text-emerald-500 mb-3 opacity-80" />
          <h4 className="text-lg font-semibold text-slate-700 dark:text-slate-200">No matching recommendations</h4>
          <p className="text-xs text-slate-400 mt-1">Try resetting your filters or search query.</p>
        </div>
      ) : (
        <div className="space-y-4">
          {filteredRecs.map((rec) => {
            const isApproved = rec.status === 'approved' || rec.status === 'edited';
            const isRejected = rec.status === 'rejected';
            const isIgnored = rec.status === 'ignored';

            return (
              <div
                key={rec.id}
                className={`bg-white dark:bg-[#05142e]/80 backdrop-blur-sm p-5 rounded-2xl border transition-all duration-300 relative overflow-hidden ${
                  isApproved 
                    ? 'border-emerald-500/50 bg-emerald-50/10 dark:bg-emerald-950/10 shadow-sm'
                    : isRejected
                    ? 'border-rose-500/40 bg-rose-50/10 dark:bg-rose-950/10 opacity-75'
                    : isIgnored
                    ? 'border-slate-300 dark:border-slate-700 opacity-60'
                    : 'border-slate-200 dark:border-[#1a325a] hover:border-blue-400 dark:hover:border-blue-500 shadow-sm hover:shadow-md'
                }`}
              >
                {/* Status Indicator Bar */}
                <div className={`absolute top-0 left-0 w-1.5 h-full ${
                  isApproved ? 'bg-emerald-500' : isRejected ? 'bg-rose-500' : isIgnored ? 'bg-slate-400' : 'bg-indigo-500'
                }`} />

                <div className="pl-3 space-y-4">
                  {/* Top Line: Category, Title, Severity, Confidence Badge */}
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                    <div className="flex items-center gap-2.5 flex-wrap">
                      <span className="px-2.5 py-1 bg-slate-100 dark:bg-[#0a1e45] text-slate-700 dark:text-slate-300 rounded-lg text-xs font-semibold flex items-center gap-1.5 border border-slate-200 dark:border-[#1a325a]">
                        {rec.category === 'Duplicates' && <Copy className="w-3.5 h-3.5 text-amber-500" />}
                        {rec.category === 'Anomalies' && <Activity className="w-3.5 h-3.5 text-rose-500" />}
                        {rec.category === 'Rule Violations' && <AlertTriangle className="w-3.5 h-3.5 text-orange-500" />}
                        {rec.category === 'Inconsistencies' && <SlidersHorizontal className="w-3.5 h-3.5 text-purple-500" />}
                        {rec.category === 'Missing Values' && <HelpCircle className="w-3.5 h-3.5 text-blue-500" />}
                        {rec.category}
                      </span>

                      <h4 className="text-base font-bold text-slate-900 dark:text-white">
                        {rec.issueTitle}
                      </h4>

                      <span className={`px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider ${
                        rec.severity === 'High' 
                          ? 'bg-rose-100 text-rose-700 dark:bg-rose-500/20 dark:text-rose-300' 
                          : 'bg-amber-100 text-amber-700 dark:bg-amber-500/20 dark:text-amber-300'
                      }`}>
                        {rec.severity} Severity
                      </span>

                      {rec.status === 'edited' && (
                        <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-purple-100 text-purple-700 dark:bg-purple-500/20 dark:text-purple-300">
                          User Edited
                        </span>
                      )}
                    </div>

                    {/* Confidence Meter Badge (C.2) */}
                    <div className="flex items-center gap-2">
                      <div className="flex flex-col items-end">
                        <span className="text-[10px] text-slate-400 font-medium">Confidence Score</span>
                        <div className="flex items-center gap-1.5">
                          <div className="w-16 h-2 bg-slate-100 dark:bg-[#0a1e45] rounded-full overflow-hidden">
                            <div
                              className={`h-full rounded-full ${
                                rec.confidenceLevel === 'High' ? 'bg-emerald-500' : rec.confidenceLevel === 'Medium' ? 'bg-amber-500' : 'bg-rose-500'
                              }`}
                              style={{ width: `${rec.confidence}%` }}
                            />
                          </div>
                          <span className={`text-xs font-bold ${
                            rec.confidenceLevel === 'High' ? 'text-emerald-500' : rec.confidenceLevel === 'Medium' ? 'text-amber-500' : 'text-rose-500'
                          }`}>
                            {rec.confidence}% ({rec.confidenceLevel})
                          </span>
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Explanation & Reason (C.3) */}
                  <div className="bg-slate-50 dark:bg-[#0a1e45]/60 p-3.5 rounded-xl border border-slate-100 dark:border-[#1a325a]/60 space-y-2">
                    <div className="flex items-start gap-2">
                      <Info className="w-4 h-4 text-blue-500 flex-shrink-0 mt-0.5" />
                      <div>
                        <p className="text-xs font-semibold text-slate-700 dark:text-slate-200">
                          {rec.explanation}
                        </p>
                        <p className="text-[11px] text-slate-500 dark:text-[#8ba3c9] mt-0.5">
                          <span className="font-medium text-slate-600 dark:text-slate-400">Reason:</span> {rec.reason}
                        </p>
                      </div>
                    </div>

                    <div className="flex items-center gap-2 pt-1 text-[11px] text-slate-400">
                      <span className="px-2 py-0.5 bg-slate-200/60 dark:bg-[#1a325a]/60 rounded text-slate-600 dark:text-slate-300 font-mono">
                        Detector: {rec.detectionMethod}
                      </span>
                      {rec.rowId && rec.rowId !== 'Multiple' && (
                        <span>Row: #{rec.rowId}</span>
                      )}
                      <span>Column: <strong className="text-slate-700 dark:text-slate-300">{rec.column}</strong></span>
                    </div>
                  </div>

                  {/* Value Diff Box & Proposed Action (C.3 & C.4) */}
                  <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 pt-1">
                    <div className="flex items-center gap-3 flex-wrap">
                      <div className="px-3 py-1.5 bg-rose-50 dark:bg-rose-950/30 border border-rose-200 dark:border-rose-900/40 rounded-lg text-xs">
                        <span className="text-[10px] text-rose-500 dark:text-rose-400 block font-bold uppercase">Original Value</span>
                        <span className="font-mono font-semibold text-rose-700 dark:text-rose-300">
                          {rec.currentValue || '<empty>'}
                        </span>
                      </div>

                      <ArrowRight className="w-4 h-4 text-slate-400" />

                      <div className="px-3 py-1.5 bg-emerald-50 dark:bg-emerald-950/30 border border-emerald-200 dark:border-emerald-900/40 rounded-lg text-xs">
                        <span className="text-[10px] text-emerald-600 dark:text-emerald-400 block font-bold uppercase">
                          {rec.status === 'edited' ? 'User Custom Value' : 'Recommended Cleaning'}
                        </span>
                        <span className="font-mono font-semibold text-emerald-700 dark:text-emerald-300">
                          {rec.userCustomValue !== null ? rec.userCustomValue : rec.suggestedValue}
                        </span>
                      </div>
                    </div>

                    {/* Action Buttons (C.4) */}
                    <div className="flex items-center gap-2">
                      <button
                        onClick={() => {
                          approveRecommendation(rec.id);
                          showToast(`Approved: ${rec.issueTitle}`);
                        }}
                        className={`px-3.5 py-1.5 text-xs font-bold rounded-xl flex items-center gap-1.5 transition-all ${
                          isApproved
                            ? 'bg-emerald-600 text-white shadow-md shadow-emerald-600/30'
                            : 'bg-emerald-50 dark:bg-emerald-950/40 text-emerald-700 dark:text-emerald-300 hover:bg-emerald-600 hover:text-white border border-emerald-200 dark:border-emerald-800'
                        }`}
                      >
                        <CheckCircle2 className="w-4 h-4" />
                        {isApproved ? 'Approved ✓' : 'Approve'}
                      </button>

                      <button
                        onClick={() => {
                          rejectRecommendation(rec.id);
                          showToast(`Rejected: ${rec.issueTitle}`);
                        }}
                        className={`px-3 py-1.5 text-xs font-semibold rounded-xl flex items-center gap-1.5 transition-all ${
                          isRejected
                            ? 'bg-rose-600 text-white'
                            : 'bg-rose-50 dark:bg-rose-950/40 text-rose-700 dark:text-rose-300 hover:bg-rose-600 hover:text-white border border-rose-200 dark:border-rose-800'
                        }`}
                      >
                        <XCircle className="w-4 h-4" />
                        Reject
                      </button>

                      <button
                        onClick={() => {
                          ignoreRecommendation(rec.id);
                          showToast(`Ignored: ${rec.issueTitle}`);
                        }}
                        className={`px-3 py-1.5 text-xs font-semibold rounded-xl flex items-center gap-1.5 transition-all ${
                          isIgnored
                            ? 'bg-slate-600 text-white'
                            : 'bg-slate-100 dark:bg-[#0a1e45] text-slate-600 dark:text-slate-300 hover:bg-slate-200 dark:hover:bg-[#1a325a] border border-slate-200 dark:border-[#1a325a]'
                        }`}
                      >
                        <MinusCircle className="w-4 h-4" />
                        Ignore
                      </button>

                      <button
                        onClick={() => handleOpenEdit(rec)}
                        className="px-3 py-1.5 text-xs font-semibold rounded-xl bg-slate-100 dark:bg-[#0a1e45] text-slate-700 dark:text-slate-300 hover:bg-indigo-50 dark:hover:bg-indigo-950/40 hover:text-indigo-600 border border-slate-200 dark:border-[#1a325a] flex items-center gap-1.5 transition-colors"
                      >
                        <Edit3 className="w-3.5 h-3.5" />
                        Edit
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Sticky Bottom Execution Banner */}
      <div className="fixed bottom-0 left-0 right-0 z-30 bg-white/95 dark:bg-[#05142e]/95 backdrop-blur-md border-t border-slate-200 dark:border-[#1a325a] py-3.5 px-6 shadow-2xl">
        <div className="max-w-7xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-3">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-full bg-emerald-100 dark:bg-emerald-500/20 text-emerald-600 dark:text-emerald-400 flex items-center justify-center font-bold text-sm">
              {counts.approved}
            </div>
            <div>
              <h5 className="text-sm font-bold text-slate-900 dark:text-white">
                {counts.approved} Cleaning Operations Approved
              </h5>
              <p className="text-xs text-slate-500 dark:text-[#8ba3c9]">
                {counts.pending} recommendations remaining in pending review.
              </p>
            </div>
          </div>

          <div className="flex items-center gap-3">
            <Link
              to="/preview"
              className="px-5 py-2.5 bg-slate-100 dark:bg-[#0a1e45] text-slate-700 dark:text-slate-300 hover:bg-slate-200 rounded-xl text-xs font-semibold border border-slate-200 dark:border-[#1a325a] transition-colors"
            >
              Back to Preview
            </Link>

            <button
              onClick={handleExecuteAndProceed}
              disabled={counts.approved === 0}
              className={`px-7 py-2.5 rounded-xl text-xs font-bold flex items-center gap-2 shadow-lg transition-all ${
                counts.approved > 0
                  ? 'bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-500 hover:to-indigo-500 text-white shadow-blue-600/25 hover:scale-[1.02] active:scale-[0.98]'
                  : 'bg-slate-300 dark:bg-slate-800 text-slate-500 cursor-not-allowed'
              }`}
            >
              <span>Apply Approved Operations & Preview Cleaned Dataset</span>
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      </div>

      {/* Interactive Edit Modal */}
      {editingRec && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4 animate-fade-in">
          <div className="bg-white dark:bg-[#05142e] border border-slate-200 dark:border-[#1a325a] rounded-2xl p-6 max-w-lg w-full shadow-2xl space-y-5">
            <div className="flex items-center justify-between border-b border-slate-100 dark:border-[#1a325a] pb-3">
              <h3 className="text-lg font-bold text-slate-900 dark:text-white flex items-center gap-2">
                <Edit3 className="w-5 h-5 text-indigo-500" />
                Customize Cleaning Action
              </h3>
              <button
                onClick={() => setEditingRec(null)}
                className="text-slate-400 hover:text-slate-600 dark:hover:text-white"
              >
                ✕
              </button>
            </div>

            <div className="space-y-4 text-xs">
              <div>
                <label className="text-slate-400 font-medium block mb-1">Issue</label>
                <p className="font-semibold text-slate-800 dark:text-white">{editingRec.issueTitle}</p>
                <p className="text-slate-500 dark:text-[#8ba3c9] mt-0.5">{editingRec.explanation}</p>
              </div>

              <div>
                <label className="text-slate-400 font-medium block mb-1">Original Current Value</label>
                <div className="p-2.5 bg-slate-50 dark:bg-[#0a1e45] rounded-xl font-mono text-slate-700 dark:text-slate-300">
                  {editingRec.currentValue || '<empty>'}
                </div>
              </div>

              <div>
                <label className="text-slate-400 font-medium block mb-1">Select Cleaning Strategy</label>
                <select
                  value={editAction}
                  onChange={(e) => setEditAction(e.target.value)}
                  className="w-full p-2.5 bg-slate-50 dark:bg-[#0a1e45] border border-slate-200 dark:border-[#1a325a] rounded-xl text-slate-800 dark:text-white focus:outline-none focus:border-blue-500"
                >
                  <option value="replace_value">Replace with Custom / Corrected Value</option>
                  <option value="remove_row">Remove Row Entirely</option>
                  <option value="clamp_value">Clamp to Allowed Range</option>
                  <option value="impute">Impute (Mean / Median / Mode)</option>
                  <option value="recalculate_cross_column">Recalculate Cross-Column Formula</option>
                </select>
              </div>

              {editAction !== 'remove_row' && (
                <div>
                  <label className="text-slate-400 font-medium block mb-1">Custom Value</label>
                  <input
                    type="text"
                    value={editValue}
                    onChange={(e) => setEditValue(e.target.value)}
                    placeholder="Enter custom replacement value..."
                    className="w-full p-2.5 bg-slate-50 dark:bg-[#0a1e45] border border-slate-200 dark:border-[#1a325a] rounded-xl text-slate-800 dark:text-white font-mono focus:outline-none focus:border-blue-500"
                  />
                </div>
              )}
            </div>

            <div className="flex items-center justify-end gap-3 pt-3 border-t border-slate-100 dark:border-[#1a325a]">
              <button
                onClick={() => setEditingRec(null)}
                className="px-4 py-2 bg-slate-100 dark:bg-[#0a1e45] text-slate-700 dark:text-slate-300 rounded-xl text-xs font-semibold hover:bg-slate-200 transition-colors"
              >
                Cancel
              </button>
              <button
                onClick={handleSaveEdit}
                className="px-5 py-2 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-500 hover:to-indigo-500 text-white rounded-xl text-xs font-bold shadow-md transition-all"
              >
                Save & Approve
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
